tasks:
  - name: Dev Server
    before: npm install -g pm2
    command: ./_dev/run-dev-env.sh
ports:
  - name: Web Proxy
    description: Application Proxy
    port: 9999
    onOpen: open-browser
  - port: 3000-9998
    onOpen: ignore
  - port: 24678
    onOpen: ignore