apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: feedwatcher
resources:
  - base/namespace.yaml
  - base/pvc.yaml
  - base/deployment.yaml
  - base/service.yaml
images:
  - name: feedwatcher
    newTag: latest
    newName: didierhoarau/feedwatcher
