name: Master Build

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # Runs a set of commands using the runners shell

      - name: Build Docker Images
        run: |
          set -e
          chmod +x _dev/*.sh
          ./_dev/docker-build-images.sh
          ./_dev/docker-publish-images.sh
