name: NPM Upgrade

on:
  schedule:
    - cron: "0 6 * * 1"

  workflow_dispatch:

jobs:
  npm-upgrade:
    uses: devopsplaybook-io/common-utils/.github/workflows/reusable-npm-upgrade.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      npm_services: '["feedwatcher-server","feedwatcher-web"]'
