name: PR Check

on:
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Agent
        run: |
          cd telepathy-agent
          npm ci
          npm run build
          npm run lint
          npm run test

      - name: Build Server
        run: |
          cd telepathy-server
          npm ci
          npm run build
          npm run lint
          npm run test

      - name: Build Web
        run: |
          cd telepathy-web
          npm ci
          npm run build
          npm run lint
          npm run test

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # Runs a set of commands using the runners shell

      - name: Build Docker Images
        run: |
          set -e
          chmod +x _dev/*.sh
          ./_dev/docker-build-images.sh
          ./_dev/docker-publish-images-beta.sh

      - name: Start Test Environment
        run: |
          set -e
          chmod +x _dev/*.sh
          npm install -g pm2
          ./_dev/run-test-env.sh
          sleep 20

      - name: E2E Test
        uses: cypress-io/github-action@v4
        with:
          working-directory: tests/tests-e2e
          browser: chrome
