name: PR Check

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-verify:
    uses: devopsplaybook-io/common-utils/.github/workflows/reusable-pr-verify.yml@main
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
