name: PR Check

on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Server
        run: |
          cd feedwatcher-server
          npm ci
          npm run build
          npm run lint
          npm run test

      - name: Build Web
        run: |
          cd feedwatcher-web
          npm ci
          npm run build
          npm run lint
          npm run test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} # Runs a set of commands using the runners shell

      - name: Build Docker Images
        run: |
          set -e
          chmod +x docs/dev/*.sh
          ./docs/dev/docker-build-images-beta.sh

      # - name: Start Test Environment
      #   run: |
      #     set -e
      #     chmod +x docs/dev/*.sh
      #     npm install -g pm2
      #     ./docs/dev/run-test-env.sh
      #     sleep 20

      # - name: E2E Test
      #   uses: cypress-io/github-action@v4
      #   with:
      #     working-directory: tests/tests-e2e
      #     browser: chrome
